const careers=[
{id:"medical-affairs",name:"医学事务",en:"Medical Affairs",summary:"连接临床证据、医学沟通与组织决策。",traits:["人与沟通","研究证据","商业策略"],skills:["文献检索","沟通表达","临床判断","项目推进"],style:{collaboration:5,ambiguity:4,pace:4,influence:5},tasks:["解读医学证据并形成沟通材料","与内外部医学专家交流","支持医学策略与跨部门协作"],gaps:["是否喜欢高频沟通和多方协作","对行业合规边界是否有基本认识"],test:"分析一份公开岗位描述，写出核心任务、已有证据和三个未知项。"},
{id:"clinical-research",name:"临床研究",en:"Clinical Research",summary:"让研究按照方案、规范和证据要求可靠推进。",traits:["研究证据","数据系统","安全质量"],skills:["科研设计","数据分析","项目推进","临床判断"],style:{collaboration:4,ambiguity:2,pace:3,influence:2},tasks:["理解研究方案和执行流程","协调研究进度与资料质量","识别偏差、风险和缺失信息"],gaps:["能否接受较强的流程和规范要求","对研究运营而非纯学术工作的感受"],test:"阅读一个临床试验登记页，复述研究问题、主要终点和执行难点。"},
{id:"medical-writing",name:"医学写作",en:"Medical Writing",summary:"把复杂医学证据转化为准确、清晰、有对象感的内容。",traits:["写作表达","研究证据"],skills:["文献检索","医学写作","临床判断"],style:{collaboration:2,ambiguity:3,pace:2,influence:2},tasks:["检索、核对并组织医学证据","根据读者和目的设计内容结构","完成撰写、编辑和多轮修订"],gaps:["是否愿意长期接受细致修改","目前有没有可以展示的写作样本"],test:"把一篇医学论文摘要改写成普通患者能理解的300字说明。"},
{id:"health-product",name:"医疗产品",en:"Health Product",summary:"从用户问题出发，连接医学、技术和业务。",traits:["人与沟通","数据系统","商业策略"],skills:["沟通表达","项目推进","数据分析","编程工具"],style:{collaboration:5,ambiguity:5,pace:5,influence:5},tasks:["访谈用户并定义真实问题","在多方限制中确定产品方案","推动设计、开发和业务协同"],gaps:["能否适应高不确定性和优先级变化","是否具备用成果说明问题的项目经历"],test:"选择一个熟悉的医疗流程，画出用户旅程并定义一个最值得解决的问题。"},
{id:"pharmacovigilance",name:"药物警戒",en:"Pharmacovigilance",summary:"围绕药品安全，处理个案、信号、规范和风险。",traits:["安全质量","研究证据","数据系统"],skills:["临床判断","文献检索","数据分析"],style:{collaboration:3,ambiguity:2,pace:3,influence:2},tasks:["收集并评估药品安全信息","处理个案、时间线和缺失信息","支持安全信号与风险管理"],gaps:["对重复、细致的信息处理是否耐受","是否愿意学习专业法规和报告规范"],test:"找一个公开药品安全案例，整理事件、时间线、因果线索和缺失信息。"}
];
const state={step:1,stage:"",skills:[],interests:[],constraint:"",experience:"",styles:{collaboration:3,ambiguity:3,pace:3,influence:3},selected:null,ranked:[]};
const stepNames=["医学背景","技能盘点","兴趣线索","工作风格","现实边界"],$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const safe=v=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function showOnly(id){["hero","catalogPanel","profilePanel","portraitPanel","resultsPanel","detailPanel","planPanel"].forEach(x=>document.getElementById(x).classList.toggle("hidden",x!==id));window.scrollTo({top:0,behavior:"smooth"})}
function renderCatalog(){$("#catalogGrid").innerHTML=careers.map(c=>`<article class="catalog-card"><span>${c.en}</span><h3>${c.name}</h3><p>${c.summary}</p><div>${c.tasks.slice(0,2).map(t=>`<small>· ${t}</small>`).join("")}</div></article>`).join("")}
function updateStep(){$$(".form-step").forEach(e=>e.classList.toggle("hidden",+e.dataset.step!==state.step));$("#stepLabel").textContent=`0${state.step} / 05`;$("#stepName").textContent=stepNames[state.step-1];$("#progressFill").style.width=`${state.step*20}%`;$("#backButton").classList.toggle("invisible",state.step===1);$("#nextButton").innerHTML=state.step===5?'生成画像 <span>→</span>':'继续 <span>→</span>';$("#formError").textContent=""}
function validate(){if(state.step===1&&!state.stage)return"请选择你目前的阶段";if(state.step===2&&!state.skills.length)return"请至少选择一项真实使用过的技能";if(state.step===3&&!state.interests.length)return"请至少选择一项兴趣线索";if(state.step===5&&!state.constraint)return"请选择一个现实限制";return""}
function styleLabel(k,v){const x={collaboration:["独立深潜","平衡协作","协作连接"],ambiguity:["偏好规则","弹性适中","拥抱变化"],pace:["稳定节奏","张弛平衡","快速行动"],influence:["证据分析","分析决策兼顾","影响决策"]}[k];return v<=2?x[0]:v>=4?x[2]:x[1]}
function renderPortrait(){state.experience=$("#experience").value.trim();$$('[data-style]').forEach(r=>state.styles[r.dataset.style]=+r.value);const labels=Object.entries(state.styles).map(([k,v])=>styleLabel(k,v));$("#portraitTitle").textContent=`${labels[0]} · ${labels[1]}`;$("#portraitNarrative").textContent=`你更接近“${labels.join("、")}”的工作方式。已有技能和兴趣可以形成转行起点，但仍需要通过真实任务验证。`;const names={collaboration:"协作倾向",ambiguity:"变化适应",pace:"行动速度",influence:"决策影响"};$("#traitBars").innerHTML=Object.entries(state.styles).map(([k,v])=>`<div><span>${names[k]}</span><i><b style="width:${v*20}%"></b></i><em>${v}/5</em></div>`).join("");$("#skillTags").innerHTML=state.skills.map(x=>`<span>${safe(x)}</span>`).join("")+(state.experience?"<span>有经历描述</span>":"");const unknowns=[state.experience?"经历能否转译成目标岗位认可的成果":"尚未提供可验证的项目或成果",state.skills.includes("数据分析")?"数据能力的具体工具与深度":"数据工具基础尚不明确",`“${state.constraint}”对选择的实际影响`];$("#unknownList").innerHTML=unknowns.map(x=>`<li>${safe(x)}</li>`).join("");showOnly("portraitPanel")}
function score(c){let n=30;const sm=c.skills.filter(x=>state.skills.includes(x)),im=c.traits.filter(x=>state.interests.includes(x)),reasons=[];n+=sm.length*8+im.length*10;Object.keys(state.styles).forEach(k=>n+=Math.max(0,5-Math.abs(state.styles[k]-c.style[k]))*1.3);if(sm.length)reasons.push(`已有 ${sm.slice(0,2).join("、")} 的使用经验`);if(im.length)reasons.push(`兴趣指向 ${im.join("、")}`);if(!reasons.length)reasons.push("作为对照方向，帮助你澄清真正偏好");return{...c,score:Math.min(94,Math.round(n)),reasons,skillMatches:sm}}
function renderResults(){state.ranked=careers.map(score).sort((a,b)=>b.score-a.score).slice(0,3);$("#profileSummary").innerHTML=[state.stage,...state.interests,state.constraint].map(x=>`<span>${safe(x)}</span>`).join("");$("#careerGrid").innerHTML=state.ranked.map((c,i)=>`<article class="career-card"><div class="card-top"><span class="rank">Hypothesis 0${i+1}</span><strong>${c.score}%</strong></div><h3>${c.name}</h3><p class="en">${c.en}</p><p class="reason">${c.summary}</p><div class="evidence"><strong>为什么值得探索</strong><br>${c.reasons.join("；")}<br><b>待验证：</b>${c.gaps[0]}</div><button class="primary-button compact detail-button" data-id="${c.id}">查看职业详情 <span>→</span></button></article>`).join("");$$('.detail-button').forEach(b=>b.onclick=()=>openDetail(b.dataset.id));showOnly("resultsPanel")}
function openDetail(id){const c=state.ranked.find(x=>x.id===id)||score(careers.find(x=>x.id===id));state.selected=id;$("#detailEn").textContent=c.en;$("#detailTitle").textContent=c.name;$("#detailSummary").textContent=c.summary;$("#detailScore").textContent=`${c.score}%`;$("#detailTasks").innerHTML=c.tasks.map(x=>`<li>${x}</li>`).join("");$("#detailEvidence").innerHTML=c.reasons.map(x=>`<li>${x}</li>`).join("");const missing=c.skills.filter(x=>!state.skills.includes(x)).slice(0,2).map(x=>`尚未看到“${x}”的使用证据`);$("#detailGaps").innerHTML=[...c.gaps,...missing].map(x=>`<li>${x}</li>`).join("");showOnly("detailPanel")}
function openPlan(){const c=careers.find(x=>x.id===state.selected);$("#planTitle").textContent=`验证“${c.name}”是否值得继续`;$("#planIntro").textContent="每天约30分钟。不要求立刻转行，只要求留下比想象更可靠的证据。";const ds=[["写下假设",`记录你对${c.name}的三个想象和最担心的一件事。`],["观察岗位","阅读3份真实岗位描述，只提取反复出现的任务与要求。"],["完成最小任务",c.test],["观察从业者","找一篇从业者公开分享，整理其获得能量与承受压力的部分。"],["翻译医学经历",state.experience?`将“${state.experience}”改写成目标岗位能理解的能力证据。`:"选择一段医学经历，用“情境—行动—结果”写成能力证据。"],["核对现实边界",`确认“${state.constraint}”是否与这个方向冲突。`],["形成下一步","记录吸引我的、消耗我的、仍不知道的；决定继续、搁置或换方向。"]];$("#timeline").innerHTML=ds.map(([t,p],i)=>`<div class="day"><span class="day-number">${i+1}</span><div><h3>${t}</h3><p>${safe(p)}</p></div></div>`).join("");$("#saveMessage").classList.add("hidden");showOnly("planPanel")}
$("#startButton").onclick=()=>showOnly("catalogPanel");$("#buildProfileButton").onclick=()=>showOnly("profilePanel");$("#seeResultsButton").onclick=renderResults;$("#makePlanButton").onclick=openPlan;$("#backToResults").onclick=()=>showOnly("resultsPanel");$("#backToDetail").onclick=()=>openDetail(state.selected);$("#restartButton").onclick=()=>{state.step=1;updateStep();showOnly("profilePanel")};$("#finishButton").onclick=()=>$("#saveMessage").classList.remove("hidden");
$$(".option-grid").forEach(g=>g.onclick=e=>{const b=e.target.closest(".choice");if(!b)return;const n=g.dataset.name,v=b.dataset.value;if(g.dataset.mode==="multi"){if(state[n].includes(v)){state[n]=state[n].filter(x=>x!==v);b.classList.remove("selected")}else if(state[n].length<+g.dataset.limit){state[n].push(v);b.classList.add("selected")}else $("#formError").textContent=`最多选择${g.dataset.limit}项`}else{g.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state[n]=v}});
$("#nextButton").onclick=()=>{const e=validate();if(e){$("#formError").textContent=e;return}if(state.step<5){state.step++;updateStep()}else renderPortrait()};$("#backButton").onclick=()=>{if(state.step>1){state.step--;updateStep()}};renderCatalog();updateStep();
