const $ = (s) => document.querySelector(s);
let sessionId = new URLSearchParams(location.search).get("session_id"); let state = null;
const esc = (v) => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(url, options) { const r = await fetch(url, options); const raw = await r.text(); let body; try { body = JSON.parse(raw); } catch (_) { throw new Error(`服务返回了非 JSON 响应（HTTP ${r.status}）。请确认只启动了一份本地服务后刷新页面。`); } if (!r.ok) throw new Error(body.error || "请求失败"); return body; }
function addMessage(text, who = "assistant") { const node = document.createElement("article"); node.className = `message ${who}`; node.textContent = text; $("#messages").append(node); node.scrollIntoView({block:"end", behavior:"smooth"}); }
async function domainAction(body) { try { const x=await api(`/api/conversations/${encodeURIComponent(sessionId)}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); render(x); } catch(e) { $("#error").textContent=e.message; } }
function renderActivityCards() { const proposals=(state?.activity_proposals||[]).filter(p=>p.status==="needs_user_confirmation"); if(!proposals.length) { const question=state?.pending_questions?.[0]; return question?`<p class="subtle">下一步：${esc(question)}</p>`:""; } const card=(p)=>{const c=p.components; const doing=[...(c.actions||[]),...(c.objects||[])].join("、")||"待补"; const method=[...(c.methods||[]),...(c.tools||[]),...(c.techniques||[])].join("、")||"未注明"; const mode=({independent:"独立完成",supervised:"在指导下完成",shared:"与他人共同完成",unknown:"待你确认"}[p.execution_mode]); const range=({partial:"部分步骤",full:"完整范围",unknown:"范围待确认"}[p.scope.coverage]); const warning=p.semantic_warnings?.length?`<p class="quote">需要你核实：${esc(p.semantic_warnings.join("；"))}</p>`:""; return `<section class="activity-card" data-proposal="${esc(p.proposal_id)}"><b>活动提议</b><p><span>做了什么：</span>${esc(doing)}</p><p><span>方法与工具：</span>${esc(method)}</p><p><span>执行方式：</span>${mode} · ${range}</p><p class="quote">原文依据：${esc(p.evidence_quote)}</p>${warning}<button data-activity-confirm="${esc(p.proposal_id)}" class="primary">确认</button><button data-activity-reject="${esc(p.proposal_id)}">拒绝</button><button data-activity-edit="${esc(p.proposal_id)}">在聊天修改</button><button data-activity-split="${esc(p.proposal_id)}">拆分</button><label><input type="checkbox" data-activity-merge="${esc(p.proposal_id)}"> 合并候选</label></section>`;}; return `<details class="activity-cards"><summary>查看核对细节（${proposals.length} 项待确认活动）</summary>${proposals.map(card).join("")}<button id="confirmAllActivities" class="primary">确认所选活动</button><button id="mergeActivities">合并勾选活动</button></details>`; }
function bindActivityCards() { document.querySelectorAll("[data-activity-confirm]").forEach(b=>b.onclick=()=>send({action:"confirm_activity_proposals",proposal_ids:[b.dataset.activityConfirm]})); document.querySelectorAll("[data-activity-reject]").forEach(b=>b.onclick=()=>send({action:"reject_activity_proposal",proposal_id:b.dataset.activityReject})); document.querySelectorAll("[data-activity-edit]").forEach(b=>b.onclick=()=>{const p=state.activity_proposals.find(x=>x.proposal_id===b.dataset.activityEdit); const action=(p?.components?.actions||[]).join("、")||"这项活动"; $("#messageInput").value=`请修改${action}这项活动：`; $("#messageInput").focus();}); document.querySelectorAll("[data-activity-split]").forEach(b=>b.onclick=()=>{const p=state.activity_proposals.find(x=>x.proposal_id===b.dataset.activitySplit); const actions=p.components.actions||[]; if(actions.length<2){$("#messageInput").value="请把这项活动拆成两步，分别说明每一步做了什么、是否独立完成以及范围。"; $("#messageInput").focus(); return;} domainAction({action:"split_activity_proposal",proposal_id:p.proposal_id,component_groups:actions.map(action=>({...p.components,actions:[action]}))});}); $("#confirmAllActivities")?.addEventListener("click",()=>send({action:"confirm_activity_proposals",proposal_ids:[...document.querySelectorAll("[data-activity-merge]:checked")].map(x=>x.dataset.activityMerge)})); $("#mergeActivities")?.addEventListener("click",()=>domainAction({action:"merge_activity_proposals",proposal_ids:[...document.querySelectorAll("[data-activity-merge]:checked")].map(x=>x.dataset.activityMerge)})); }
function toneLabel(tone) { return ({Conservative:"保守",Professional:"专业", "High-impact":"更有力度"}[tone]||tone); }
function renderRewriteCards() { const claims=(state?.generated_claims||[]).filter(c=>c.schema_version==="bullet-claim-v2"); if(!claims.length) return ""; const rewriteById=new Map((state?.rewrite_candidates||[]).map(x=>[x.claim_id,x])); const sourceClaims=claims.filter(c=>!rewriteById.has(c.claim_id)); const alternatives=claims.filter(c=>rewriteById.has(c.claim_id)); const sourceCard=(c)=>{const control=(tone,primary=false)=>{const existing=alternatives.find(item=>{const meta=rewriteById.get(item.claim_id); return meta?.source_claim_id===c.claim_id && meta?.tone===tone;}); return existing?`<button disabled>${esc(toneLabel(tone))}候选已生成</button>`:`<button data-rewrite="${esc(c.claim_id)}" data-tone="${esc(tone)}" class="${primary?"primary":""}">生成${esc(toneLabel(tone))}版</button>`;}; return `<section class="activity-card wording-source"><b>当前已审计版本</b><p>${esc(c.wording)}</p><p class="quote">选择一个表达方向，系统会生成新版本并再次审计；不会覆盖当前版本。</p><div class="rewrite-actions">${control("Conservative")}${control("Professional",true)}${control("High-impact")}</div></section>`;}; const alternativeCard=(c)=>{const meta=rewriteById.get(c.claim_id); const ready=c.verification_status==="ready"; const selected=Boolean(meta?.selected); return `<section class="activity-card rewrite-candidate ${selected?"selected-candidate":""}"><p><b>${esc(toneLabel(meta?.tone))}候选</b>${selected?" · 已用于右侧预览":""}</p><p>${esc(c.wording)}</p><p class="quote">${ready?"已通过 ClaimGate":"尚未通过 ClaimGate，不能用于预览"}</p>${ready?`<button data-select-rewrite="${esc(c.claim_id)}" class="${selected?"selected":"primary"}">${selected?"正在使用":"使用这版"}</button>`:""}</section>`;}; return `<div class="activity-cards rewrite-workspace"><h3>措辞工作区</h3>${sourceClaims.map(sourceCard).join("")}${alternatives.length?`<h4>已生成的候选版本</h4>${alternatives.map(alternativeCard).join("")}`:""}</div>`; }
function bindRewriteCards() { document.querySelectorAll("[data-rewrite]").forEach(b=>b.onclick=()=>domainAction({action:"rewrite_claim",source_claim_id:b.dataset.rewrite,tone:b.dataset.tone,instruction:`生成${toneLabel(b.dataset.tone)}版；保持已确认的事实、责任和范围不变。`})); document.querySelectorAll("[data-select-rewrite]").forEach(b=>b.onclick=()=>domainAction({action:"select_rewrite_candidate",claim_id:b.dataset.selectRewrite})); }
function render(response) { state = response.state || state; if (response.assistant_message) addMessage(response.assistant_message); const doc = response.resume_document || state?.resume_document; const audit = response.audit_status || {ready:0,not_ready:0}; $("#audit").textContent = `审计状态：${audit.ready} 条 ready，${audit.not_ready} 条待处理`; const exps = doc?.research_experience || []; $("#resumePreview").innerHTML = exps.length ? exps.map(x => `<section><h3>${esc(x.title)}</h3>${x.bullets.map(b => `<p>• ${esc(b.text)}</p>`).join("") || "<p class='subtle'>尚无可展示的已审计要点</p>"}</section>`).join("") : "<section><h3>实时预览</h3><p class='subtle'>完成事实确认、目标方向和 ClaimGate 审计后，这里会出现可使用的简历要点。</p></section>"; $("#openResumeBeta").href = `../resume-beta/index.html?session_id=${encodeURIComponent(sessionId)}`;
  const factCard=$("#factCard"); const showFactStep=state?.stage === "fact_confirmation"; const showRoles=state?.stage === "representative_sample" || state?.stage === "composition"; $("#roleChips").classList.toggle("hidden",!showRoles);
  if (state?.extracted_draft && showFactStep) { const f=state.extracted_draft.extracted_facts; factCard.classList.remove("hidden"); factCard.innerHTML=`<details><summary>查看当前理解与核对细节</summary><p>项目整体角色：<b>${esc(f.role?.responsibility_level)}</b></p><p>行动：${esc((f.actions||[]).join("、")||"待补")}</p><p>方法/工具：${esc([...(f.methods||[]),...(f.tools||[])].join("、")||"待补")}</p><p class="subtle">你可以直接在聊天中补充、修正或发送“确认”；这里仅用于查看与逐项核对。</p>${renderActivityCards()}</details>`; bindActivityCards(); }
  else if (state?.confirmed_canonical_experience) { factCard.classList.remove("hidden"); factCard.innerHTML=`<details><summary>已确认经历</summary><p>${esc((state.confirmed_canonical_experience.actions||[]).join("、")||"已确认事实")}</p></details>${state?.stage === "factual_audit" ? renderRewriteCards() : ""}`; bindRewriteCards(); }
  else factCard.classList.add("hidden"); }
async function startNewConversation() { const x=await api("/api/conversations", {method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}); sessionId=x.session_id; history.replaceState(null,"",`?session_id=${encodeURIComponent(sessionId)}`); state=x.state; $("#messages").innerHTML=""; addMessage("请先描述一段真实、可核实的医学相关经历。"); render(x); }
async function load() { if (!sessionId) return startNewConversation(); const x=await api(`/api/conversations/${encodeURIComponent(sessionId)}`); state=x.state; const hasHistory=(state?.conversation_turns||[]).length>0 || Boolean(state?.confirmed_canonical_experience); if (hasHistory) addMessage("已恢复此前会话；你可以继续补充或修改，也可以点击“新建经历”开始空白会话。"); render(x); }
async function send(extra={}) { const text=$("#messageInput").value.trim(); $("#error").textContent=""; if(text) addMessage(text,"user"); try { const x=await api(`/api/conversations/${encodeURIComponent(sessionId)}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,consent_confirmed:$("#consent").checked,...extra})}); $("#messageInput").value=""; render(x); } catch(e) { $("#error").textContent=e.message; } }
$("#messageForm").onsubmit=(e)=>{e.preventDefault(); send();}; document.querySelectorAll("[data-role]").forEach(b=>b.onclick=()=>send({action:"select_role_packs",role_packs:[b.dataset.role]})); $("#newConversation").onclick=()=>startNewConversation().catch(e=>$("#error").textContent=e.message); load().catch(e=>$("#error").textContent=e.message);
