const $ = (s) => document.querySelector(s);
let sessionId = new URLSearchParams(location.search).get("session_id"); let state = null; const selectedRoles = new Set();
const esc = (v) => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(url, options) { const r = await fetch(url, options); const body = await r.json(); if (!r.ok) throw new Error(body.error || "请求失败"); return body; }
function addMessage(text, who = "assistant") { const node = document.createElement("article"); node.className = `message ${who}`; node.textContent = text; $("#messages").append(node); node.scrollIntoView({block:"end", behavior:"smooth"}); }
function proposalPayload(p) { return {evidence_quote:p.evidence_quote,components:p.components,ownership_level:p.ownership_level,execution_mode:p.execution_mode,coverage:p.scope.coverage,scope_note:p.scope.note}; }
async function updateProposals(proposals) { try { const x=await api(`/api/conversations/${encodeURIComponent(sessionId)}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"update_activity_proposals",activity_proposals:proposals.map(proposalPayload)})}); render(x); } catch(e) { $("#error").textContent=e.message; } }
async function domainAction(body) { try { const x=await api(`/api/conversations/${encodeURIComponent(sessionId)}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); render(x); } catch(e) { $("#error").textContent=e.message; } }
function renderActivityCards() { const proposals=(state?.activity_proposals||[]).filter(p=>p.status==="needs_user_confirmation"); if(!proposals.length) { const question=state?.pending_questions?.[0]; return question?`<p class="subtle">下一步：${esc(question)}</p>`:""; } const card=(p)=>{const c=p.components; const doing=[...(c.actions||[]),...(c.objects||[])].join("、")||"待补"; const method=[...(c.methods||[]),...(c.tools||[]),...(c.techniques||[])].join("、")||"未注明"; const mode=({independent:"独立完成",supervised:"在指导下完成",shared:"与他人共同完成",unknown:"待你确认"}[p.execution_mode]); const range=({partial:"部分步骤",full:"完整范围",unknown:"范围待确认"}[p.scope.coverage]); const warning=p.semantic_warnings?.length?`<p class="quote">需要你核实：${esc(p.semantic_warnings.join("；"))}</p>`:""; return `<section class="activity-card" data-proposal="${esc(p.proposal_id)}"><b>活动提议</b><p><span>做了什么：</span>${esc(doing)}</p><p><span>方法与工具：</span>${esc(method)}</p><p><span>执行方式：</span>${mode} · ${range}</p><p class="quote">原文依据：${esc(p.evidence_quote)}</p>${warning}<button data-activity-confirm="${esc(p.proposal_id)}" class="primary">确认</button><button data-activity-reject="${esc(p.proposal_id)}">拒绝</button><button data-activity-edit="${esc(p.proposal_id)}">修改</button><button data-activity-split="${esc(p.proposal_id)}">拆分</button><label><input type="checkbox" data-activity-merge="${esc(p.proposal_id)}"> 合并候选</label></section>`;}; return `<div class="activity-cards"><h3>待确认活动</h3>${proposals.map(card).join("")}<button id="confirmAllActivities" class="primary">确认所选活动</button><button id="mergeActivities">合并勾选活动</button></div>`; }
function bindActivityCards() { document.querySelectorAll("[data-activity-confirm]").forEach(b=>b.onclick=()=>send({action:"confirm_activity_proposals",proposal_ids:[b.dataset.activityConfirm]})); document.querySelectorAll("[data-activity-reject]").forEach(b=>b.onclick=()=>send({action:"reject_activity_proposal",proposal_id:b.dataset.activityReject})); document.querySelectorAll("[data-activity-edit]").forEach(b=>b.onclick=()=>{const p=state.activity_proposals.find(x=>x.proposal_id===b.dataset.activityEdit); const ownership=prompt("对该任务结果的承担：参与 / 负责子任务 / 推动交付",({contributed:"参与",owned_component:"负责子任务",led_delivery:"推动交付",accountable:"整体负责",unknown:""}[p.ownership_level])); const mode=prompt("执行方式：独立 / 指导 / 共同",({independent:"独立",supervised:"指导",shared:"共同",unknown:""}[p.execution_mode])); const coverage=prompt("范围：完整 / 部分",({full:"完整",partial:"部分",unknown:""}[p.scope.coverage])); if(ownership&&mode&&coverage){p.ownership_level=ownership==="负责子任务"?"owned_component":ownership==="推动交付"?"led_delivery":ownership==="整体负责"?"accountable":"contributed";p.execution_mode=mode==="独立"?"independent":mode==="共同"?"shared":"supervised";p.scope.coverage=coverage==="完整"?"full":"partial";updateProposals(state.activity_proposals.filter(x=>x.status==="needs_user_confirmation"));}}); document.querySelectorAll("[data-activity-split]").forEach(b=>b.onclick=()=>{const p=state.activity_proposals.find(x=>x.proposal_id===b.dataset.activitySplit); const actions=p.components.actions||[]; if(actions.length<2){$("#messageInput").value="请把这项活动拆成两步，分别说明每一步做了什么、是否独立完成以及范围。"; $("#messageInput").focus(); return;} domainAction({action:"split_activity_proposal",proposal_id:p.proposal_id,component_groups:actions.map(action=>({...p.components,actions:[action]}))});}); $("#confirmAllActivities")?.addEventListener("click",()=>send({action:"confirm_activity_proposals",proposal_ids:[...document.querySelectorAll("[data-activity-merge]:checked")].map(x=>x.dataset.activityMerge)})); $("#mergeActivities")?.addEventListener("click",()=>domainAction({action:"merge_activity_proposals",proposal_ids:[...document.querySelectorAll("[data-activity-merge]:checked")].map(x=>x.dataset.activityMerge)})); }
function renderRewriteCards() { const claims=(state?.generated_claims||[]).filter(c=>c.schema_version==="bullet-claim-v2"); if(!claims.length) return ""; return `<div class="activity-cards"><h3>候选措辞</h3>${claims.map(c=>`<section class="activity-card"><p>${esc(c.wording)}</p><button data-rewrite="${esc(c.claim_id)}" data-tone="Conservative">保守</button><button data-rewrite="${esc(c.claim_id)}" data-tone="Professional">专业</button><button data-rewrite="${esc(c.claim_id)}" data-tone="High-impact">更有力度</button></section>`).join("")}</div>`; }
function bindRewriteCards() { document.querySelectorAll("[data-rewrite]").forEach(b=>b.onclick=()=>{const instruction=prompt("你想怎么改？例如：专业一点，但别显得我主导项目。",""); if(instruction!==null) domainAction({action:"rewrite_claim",source_claim_id:b.dataset.rewrite,tone:b.dataset.tone,instruction});}); }
function render(response) { state = response.state || state; if (response.assistant_message) addMessage(response.assistant_message); const doc = response.resume_document || state?.resume_document; const audit = response.audit_status || {ready:0,not_ready:0}; $("#audit").textContent = `审计状态：${audit.ready} 条 ready，${audit.not_ready} 条待处理`; const exps = doc?.research_experience || []; $("#resumePreview").innerHTML = exps.map(x => `<section><h3>${esc(x.title)}</h3>${x.bullets.map(b => `<p>• ${esc(b.text)}</p>`).join("") || "<p class='subtle'>尚无可展示的已审计要点</p>"}</section>`).join(""); $("#openResumeBeta").href = `../resume-beta/index.html?session_id=${encodeURIComponent(sessionId)}`;
  if (state?.extracted_draft) { const f=state.extracted_draft.extracted_facts; $("#factCard").classList.remove("hidden"); $("#factCard").innerHTML=`<h3>待确认事实卡</h3><p>项目整体角色：<b>${esc(f.role?.responsibility_level)}</b></p><p>行动：${esc((f.actions||[]).join("、")||"待补")}</p><p>方法/工具：${esc([...(f.methods||[]),...(f.tools||[])].join("、")||"待补")}</p><button id="confirmFacts" class="primary">仅确认事实</button><button id="updateFacts">补充/修正事实</button>${renderActivityCards()}${renderRewriteCards()}`; $("#confirmFacts").onclick=()=>send({action:"confirm_facts"}); $("#updateFacts").onclick=()=>$("#messageInput").focus(); bindActivityCards(); bindRewriteCards(); }
  if (state?.stage === "representative_sample" || state?.stage === "factual_audit") $("#roleChips").classList.remove("hidden"); }
async function load() { if (!sessionId) { const x=await api("/api/conversations", {method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}); sessionId=x.session_id; history.replaceState(null,"",`?session_id=${encodeURIComponent(sessionId)}`); state=x.state; addMessage("请先描述一段真实、可核实的医学相关经历。"); render(x); } else { const x=await api(`/api/conversations/${encodeURIComponent(sessionId)}`); state=x.state; render(x); } }
async function send(extra={}) { const text=$("#messageInput").value.trim(); $("#error").textContent=""; if(text) addMessage(text,"user"); try { const x=await api(`/api/conversations/${encodeURIComponent(sessionId)}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,consent_confirmed:$("#consent").checked,...extra})}); $("#messageInput").value=""; render(x); } catch(e) { $("#error").textContent=e.message; } }
$("#messageForm").onsubmit=(e)=>{e.preventDefault(); send();}; document.querySelectorAll("[data-role]").forEach(b=>b.onclick=()=>{const r=b.dataset.role; selectedRoles.has(r)?selectedRoles.delete(r):selectedRoles.add(r); b.classList.toggle("selected",selectedRoles.has(r));}); $("#generate").onclick=()=>send({action:"select_role_packs",role_packs:[...selectedRoles]}); load().catch(e=>$("#error").textContent=e.message);
