const careers=[
{id:"ma",name:"医学事务",en:"Medical Affairs",summary:"连接医学证据、专家沟通与企业决策。",tasks:["解读临床证据并形成医学材料","与内外部医学专家开展科学交流","支持医学策略和跨部门协作"],transfer:["医学知识帮助理解疾病与治疗","科研经历可转化为证据解读能力","临床沟通可以迁移到专家交流"],gaps:["行业合规与商业环境认知","高频沟通和多项目协作经验"]},
{id:"cra",name:"临床研究",en:"Clinical Research",summary:"让研究按照方案、规范和质量要求可靠推进。",tasks:["理解研究方案与执行流程","协调中心、进度和研究资料","发现偏差、风险与缺失信息"],transfer:["理解临床流程和医学术语","科研训练支持方案理解","细致记录可迁移到质量管理"],gaps:["GCP 与研究运营流程","跨中心项目协调经验"]},
{id:"mw",name:"医学写作",en:"Medical Writing",summary:"把复杂医学证据转化为准确、清晰的内容。",tasks:["检索、核对并组织医学证据","针对不同读者设计内容结构","完成撰写、编辑与多轮修订"],transfer:["文献阅读与医学术语基础","论文写作和逻辑表达经验","判断信息准确性的专业训练"],gaps:["可展示的作品样本","不同内容类型的写作规范"]},
{id:"product",name:"医疗产品",en:"Health Product",summary:"从用户问题出发，连接医学、技术和业务。",tasks:["访谈用户并定义真实问题","设计方案与确定优先级","推动设计、开发和业务协作"],transfer:["理解医患场景与医疗流程","临床问题可转化为用户洞察","多学科协作经验"],gaps:["产品方法和商业理解","能够展示成果的项目案例"]},
{id:"pv",name:"药物警戒",en:"Pharmacovigilance",summary:"围绕药品安全处理个案、信号和风险。",tasks:["收集并评估药品安全信息","处理个案、时间线和缺失信息","支持安全信号与风险管理"],transfer:["临床判断和风险意识","病历信息整合能力","医学文献检索能力"],gaps:["药物警戒法规与报告规范","标准化安全数据库经验"]}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let target=localStorage.getItem("careerTarget")||"";
function navigate(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'})}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2200)}
function updateTarget(){const text=target||"尚未选择目标";$('#targetSummary').textContent=text;$('#profileTarget').textContent=target?`当前探索：${target}`:"暂未选择目标岗位";$('#trackerTarget').textContent=text}
function renderCareers(){$('#careerList').innerHTML=careers.map(c=>`<article><span>${c.en}</span><h2>${c.name}</h2><p>${c.summary}</p><div><small>典型任务</small>${c.tasks.slice(0,2).map(x=>`<b>· ${x}</b>`).join('')}</div><button class="link career-open" data-id="${c.id}">查看完整职业卡 →</button></article>`).join('');$$('.career-open').forEach(b=>b.onclick=()=>openCareer(b.dataset.id))}
function openCareer(id){const c=careers.find(x=>x.id===id);$('#careerDetailContent').innerHTML=`<div class="detail-hero"><span>${c.en}</span><h1>${c.name}</h1><p>${c.summary}</p><button class="primary" id="setTarget">${target===c.name?'已设为目标':'加入我的目标'}</button></div><div class="detail-cols"><article><span>日常可能在做什么</span><ul>${c.tasks.map(x=>`<li>${x}</li>`).join('')}</ul></article><article><span>医学背景如何迁移</span><ul>${c.transfer.map(x=>`<li>${x}</li>`).join('')}</ul></article><article><span>需要补充的证据</span><ul>${c.gaps.map(x=>`<li>${x}</li>`).join('')}</ul></article></div><div class="next-actions"><h2>接下来可以做什么</h2><button class="secondary" data-go="resume">针对岗位修改简历</button><button class="secondary" data-go="interview">练习 HR 面试</button><button class="secondary" data-go="growth">查看能力差距</button><a href="exploration-v1/index.html">进行短期职业验证（可选）</a></div>`;$('#setTarget').onclick=()=>{target=c.name;localStorage.setItem('careerTarget',target);updateTarget();$('#setTarget').textContent='已设为目标';toast(`已将“${target}”设为当前目标`)};$$('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));navigate('careerDetail')}
$$('#nav button,.jump,.back').forEach(b=>b.onclick=()=>navigate(b.dataset.page||b.dataset.target));
$('#polishButton').onclick=()=>{const role=$('#resumeRole').value.trim()||target,exp=$('#resumeExperience').value.trim(),jd=$('#resumeJd').value.trim();if(!role||!exp){toast('请先填写目标岗位和一段经历');return}$('#resumeOutput').innerHTML=`<span>经历转译草稿 · 仍需本人核实</span><h2>${role} 方向</h2><p><strong>原始证据：</strong>${exp}</p><div class="rewrite"><b>建议结构</b><p>在【具体情境】中，负责【你的行动】，运用医学理解、证据检索或协作能力，完成【可核实结果】。</p></div><ul><li>补充人数、周期、材料数量或交付物等可核实结果</li><li>说明你本人做了什么，不把团队成果全部归于个人</li><li>${jd?`优先回应 JD 中的要求：“${jd.slice(0,60)}${jd.length>60?'…':''}”`:'粘贴具体 JD 后才能进行针对性修改'}</li></ul>`}
const qs=["请用1—2分钟介绍你的医学背景、关键能力，以及你为什么来到今天的面试。","是什么促使你考虑离开传统临床路径？为什么是这个岗位？","请用情境—任务—行动—结果讲一次你推动他人协作的经历。","你认为自己缺少哪些行业经验？准备如何降低用人方的顾虑？"];
$$('.question').forEach((b,i)=>b.onclick=()=>{$$('.question').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#interviewQuestion').textContent=qs[i];$('#feedbackBox').classList.add('hidden')});
$('#feedbackButton').onclick=()=>{const a=$('#interviewAnswer').value.trim();if(a.length<30){toast('请先写下较完整的回答');return}const hasEvidence=/负责|完成|结果|提升|减少|参与/.test(a),hasReason=/因为|希望|选择|动机|因此/.test(a);$('#feedbackBox').innerHTML=`<span>结构反馈 · 不是标准答案</span><h3>${hasEvidence&&hasReason?'回答已经有基本证据链':'先让动机和证据更具体'}</h3><ul><li>${hasReason?'已经表达了选择或动机':'补充：为什么转行、为什么是这个岗位'}</li><li>${hasEvidence?'已经提到行动或结果':'加入一个本人实际完成的行动和可核实结果'}</li><li>结尾说明医学背景如何为目标岗位创造价值，而不是只解释为何离开医学</li></ul>`;$('#feedbackBox').classList.remove('hidden')};
renderCareers();updateTarget();
